import { Activities, Observers, Permissions, Units } from './src/constants'

const { AppleHealthKit } = require('react-native').NativeModules

const isIOS = Platform.OS === "ios"
const emptyFunction = () => { }
const emptyPromise = new Promise((resolve) => resolve([]))

export const HealthKit = {
  initHealthKit: isIOS ? AppleHealthKit.initHealthKit : emptyFunction,
  isAvailable: isIOS ? AppleHealthKit.isAvailable : () => true,

  getBiologicalSex: isIOS ? AppleHealthKit.getBiologicalSex : emptyFunction,
  getBloodType: isIOS ? AppleHealthKit.getBloodType : emptyFunction,
  getDateOfBirth: isIOS ? AppleHealthKit.getDateOfBirth : emptyFunction,
  getLatestWeight: isIOS ? AppleHealthKit.getLatestWeight : emptyFunction,
  getWeightSamples: isIOS ? AppleHealthKit.getWeightSamples : emptyFunction,
  saveWeight: isIOS ? AppleHealthKit.saveWeight : emptyFunction,
  getLatestHeight: isIOS ? AppleHealthKit.getLatestHeight : emptyFunction,
  getHeightSamples: isIOS ? AppleHealthKit.getHeightSamples : emptyFunction,
  saveHeight: isIOS ? AppleHealthKit.saveHeight : emptyFunction,
  getLatestWaistCircumference: isIOS ? AppleHealthKit.getLatestWaistCircumference : emptyFunction,
  getWaistCircumferenceSamples: isIOS ? AppleHealthKit.getWaistCircumferenceSamples : emptyFunction,
  saveWaistCircumference: isIOS ? AppleHealthKit.saveWaistCircumference : emptyFunction,
  getLatestPeakFlow: isIOS ? AppleHealthKit.getLatestPeakFlow : emptyFunction,
  getPeakFlowSamples: isIOS ? AppleHealthKit.getPeakFlowSamples : emptyFunction,
  savePeakFlow: isIOS ? AppleHealthKit.savePeakFlow : emptyFunction,
  saveLeanBodyMass: isIOS ? AppleHealthKit.saveLeanBodyMass : emptyFunction,
  getLatestBmi: isIOS ? AppleHealthKit.getLatestBmi : emptyFunction,
  getBmiSamples: isIOS ? AppleHealthKit.getBmiSamples : emptyFunction,
  saveBmi: isIOS ? AppleHealthKit.saveBmi : emptyFunction,
  getLatestBodyFatPercentage: isIOS ? AppleHealthKit.getLatestBodyFatPercentage : emptyFunction,
  getBodyFatPercentageSamples: isIOS ? AppleHealthKit.getBodyFatPercentageSamples : emptyFunction,
  getLatestLeanBodyMass: isIOS ? AppleHealthKit.getLatestLeanBodyMass : emptyFunction,
  getLeanBodyMassSamples: isIOS ? AppleHealthKit.getLeanBodyMassSamples : emptyFunction,
  getStepCount: isIOS ? AppleHealthKit.getStepCount : emptyFunction,
  getSamples: isIOS ? AppleHealthKit.getSamples : emptyFunction,
  getAnchoredWorkouts: isIOS ? AppleHealthKit.getAnchoredWorkouts : emptyFunction,
  getDailyStepCountSamples: isIOS ? AppleHealthKit.getDailyStepCountSamples : emptyFunction,
  saveSteps: isIOS ? AppleHealthKit.saveSteps : emptyFunction,
  saveWalkingRunningDistance: isIOS ? AppleHealthKit.saveWalkingRunningDistance : emptyFunction,
  getDistanceWalkingRunning: isIOS ? AppleHealthKit.getDistanceWalkingRunning : emptyFunction,
  getDailyDistanceWalkingRunningSamples: isIOS ? AppleHealthKit.getDailyDistanceWalkingRunningSamples : emptyFunction,
  getDistanceCycling: isIOS ? AppleHealthKit.getDistanceCycling : emptyFunction,
  getDailyDistanceCyclingSamples: isIOS ? AppleHealthKit.getDailyDistanceCyclingSamples : emptyFunction,
  getFlightsClimbed: isIOS ? AppleHealthKit.getFlightsClimbed : emptyFunction,
  getDailyFlightsClimbedSamples: isIOS ? AppleHealthKit.getDailyFlightsClimbedSamples : emptyFunction,
  getEnergyConsumedSamples: isIOS ? AppleHealthKit.getEnergyConsumedSamples : emptyFunction,
  getProteinSamples: isIOS ? AppleHealthKit.getProteinSamples : emptyFunction,
  getFiberSamples: isIOS ? AppleHealthKit.getFiberSamples : emptyFunction,
  getTotalFatSamples: isIOS ? AppleHealthKit.getTotalFatSamples : emptyFunction,
  saveFood: isIOS ? AppleHealthKit.saveFood : emptyFunction,
  saveWater: isIOS ? AppleHealthKit.saveWater : emptyFunction,
  getWater: isIOS ? AppleHealthKit.getWater : emptyFunction,
  saveHeartRateSample: isIOS ? AppleHealthKit.saveHeartRateSample : emptyFunction,
  getWaterSamples: isIOS ? AppleHealthKit.getWaterSamples : emptyFunction,
  getHeartRateSamples: isIOS ? AppleHealthKit.getHeartRateSamples : emptyFunction,
  getRestingHeartRate: isIOS ? AppleHealthKit.getRestingHeartRate : emptyFunction,
  getWalkingHeartRateAverage: isIOS ? AppleHealthKit.getWalkingHeartRateAverage : emptyFunction,
  getActiveEnergyBurned: isIOS ? AppleHealthKit.getActiveEnergyBurned : emptyFunction,
  getBasalEnergyBurned: isIOS ? AppleHealthKit.getBasalEnergyBurned : emptyFunction,
  getAppleExerciseTime: isIOS ? AppleHealthKit.getAppleExerciseTime : emptyFunction,
  getAppleStandTime: isIOS ? AppleHealthKit.getAppleStandTime : emptyFunction,
  getVo2MaxSamples: isIOS ? AppleHealthKit.getVo2MaxSamples : emptyFunction,
  getBodyTemperatureSamples: isIOS ? AppleHealthKit.getBodyTemperatureSamples : emptyFunction,
  getBloodPressureSamples: isIOS ? AppleHealthKit.getBloodPressureSamples : emptyFunction,
  getRespiratoryRateSamples: isIOS ? AppleHealthKit.getRespiratoryRateSamples : emptyFunction,
  getHeartRateVariabilitySamples: isIOS ? AppleHealthKit.getHeartRateVariabilitySamples : emptyFunction,
  getHeartbeatSeriesSamples: isIOS ? AppleHealthKit.getHeartbeatSeriesSamples : emptyFunction,
  getRestingHeartRateSamples: isIOS ? AppleHealthKit.getRestingHeartRateSamples : emptyFunction,
  getBloodGlucoseSamples: isIOS ? AppleHealthKit.getBloodGlucoseSamples : emptyFunction,
  getCarbohydratesSamples: isIOS ? AppleHealthKit.getCarbohydratesSamples : emptyFunction,
  saveBloodGlucoseSample: isIOS ? AppleHealthKit.saveBloodGlucoseSample : emptyFunction,
  saveCarbohydratesSample: isIOS ? AppleHealthKit.saveCarbohydratesSample : emptyFunction,
  deleteBloodGlucoseSample: isIOS ? AppleHealthKit.deleteBloodGlucoseSample : emptyFunction,
  deleteCarbohydratesSample: isIOS ? AppleHealthKit.deleteCarbohydratesSample : emptyFunction,
  getSleepSamples: isIOS ? AppleHealthKit.getSleepSamples : emptyFunction,
  getInfo: isIOS ? AppleHealthKit.getInfo : emptyFunction,
  getMindfulSession: isIOS ? AppleHealthKit.getMindfulSession : emptyFunction,
  saveMindfulSession: isIOS ? AppleHealthKit.saveMindfulSession : emptyFunction,
  getWorkoutRouteSamples: isIOS ? AppleHealthKit.getWorkoutRouteSamples : emptyFunction,
  saveWorkout: isIOS ? AppleHealthKit.saveWorkout : emptyFunction,
  getAuthStatus: isIOS ? AppleHealthKit.getAuthStatus : emptyFunction,
  getLatestBloodAlcoholContent: isIOS ? AppleHealthKit.getLatestBloodAlcoholContent : emptyFunction,
  getBloodAlcoholContentSamples: isIOS ? AppleHealthKit.getBloodAlcoholContentSamples : emptyFunction,
  saveBloodAlcoholContent: isIOS ? AppleHealthKit.saveBloodAlcoholContent : emptyFunction,
  getDistanceSwimming: isIOS ? AppleHealthKit.getDistanceSwimming : emptyFunction,
  getDailyDistanceSwimmingSamples: isIOS ? AppleHealthKit.getDailyDistanceSwimmingSamples : emptyFunction,
  getOxygenSaturationSamples: isIOS ? AppleHealthKit.getOxygenSaturationSamples : emptyFunction,
  getElectrocardiogramSamples: isIOS ? AppleHealthKit.getElectrocardiogramSamples : emptyFunction,
  saveBodyFatPercentage: isIOS ? AppleHealthKit.saveBodyFatPercentage : emptyFunction,
  saveBodyTemperature: isIOS ? AppleHealthKit.saveBodyTemperature : emptyFunction,
  getEnvironmentalAudioExposure: isIOS ? AppleHealthKit.getEnvironmentalAudioExposure : emptyFunction,
  getHeadphoneAudioExposure: isIOS ? AppleHealthKit.getHeadphoneAudioExposure : emptyFunction,
  getClinicalRecords: isIOS ? AppleHealthKit.getClinicalRecords : emptyFunction,
  getActivitySummary: isIOS ? AppleHealthKit.getActivitySummary : emptyFunction,
  getInsulinDeliverySamples: isIOS ? AppleHealthKit.getInsulinDeliverySamples : emptyFunction,
  saveInsulinDeliverySample: isIOS ? AppleHealthKit.saveInsulinDeliverySample : emptyFunction,
  deleteInsulinDeliverySample: isIOS ? AppleHealthKit.deleteInsulinDeliverySample : emptyFunction,

  // Bearable Methods
  readBucketedQuantity: isIOS ? AppleHealthKit.readBucketedQuantity : emptyPromise,
  readBucketedSleep: isIOS ? AppleHealthKit.readBucketedSleep : emptyPromise,

  Constants: {
    Activities,
    Observers,
    Permissions,
    Units,
  },
}

module.exports = HealthKit
